In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("C:\\Users\\RIYANA\\OneDrive\\New folder\\Student_Performance.csv")

In [3]:
df

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [4]:
df.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [5]:
df.isnull()

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0             False            False                       False        False   
1             False            False                       False        False   
2             False            False                       False        False   
3             False            False                       False        False   
4             False            False                       False        False   
...             ...              ...                         ...          ...   
9995          False            False                       False        False   
9996          False            False                       False        False   
9997          False            False                       False        False   
9998          False            False                       False        False   
9999          False            False                       False        False   

      Sample Question Papers Practiced  Performance Index  
0                                False              False  
1                                False              False  
2                                False              False  
3                                False              False  
4                                False              False  
...                                ...                ...  
9995                             False              False  
9996                             False              False  
9997                             False              False  
9998                             False              False  
9999                             False              False  

[10000 rows x 6 columns]

In [6]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(127)

In [8]:
df.drop_duplicates(inplace=True)
df

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[9873 rows x 6 columns]

In [9]:
df.duplicated().sum()

np.int64(0)

# encoding

In [10]:
from sklearn.preprocessing import LabelEncoder

In [11]:
encoder=LabelEncoder()

In [12]:
df["Extracurricular Activities"]=encoder.fit_transform(df["Extracurricular Activities"])

In [13]:
df

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[9873 rows x 6 columns]

# train test split

In [14]:
x=df.drop("Performance Index",axis=1)

In [15]:
y=df["Performance Index"]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x.shape

(9873, 5)

In [18]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=33)

In [19]:
xtrain.shape

(7898, 5)

In [20]:
xtest.shape

(1975, 5)

In [21]:
ytrain.shape

(7898,)

In [22]:
ytest.shape

(1975,)

# scaler

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
scaler=StandardScaler()

In [25]:
xtrain_scaled=scaler.fit_transform(xtrain)

In [26]:
xtrain.head()

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
1550              6               97                           1            9   
2744              1               41                           1            5   
3851              5               77                           0            7   
1870              2               71                           1            8   
6606              1               80                           0            9   

      Sample Question Papers Practiced  
1550                                 2  
2744                                 5  
3851                                 9  
1870                                 8  
6606                                 0

In [27]:
xtrain_scaled

array([[ 3.85655186e-01,  1.59478896e+00,  1.00405990e+00,
         1.46296450e+00, -9.08838580e-01],
       [-1.54898954e+00, -1.63470048e+00,  1.00405990e+00,
        -8.97865782e-01,  1.41294128e-01],
       [-1.27375951e-03,  4.41399871e-01, -9.95956516e-01,
         2.82549357e-01,  1.54147107e+00],
       ...,
       [ 1.54644202e+00, -1.11567539e+00, -9.95956516e-01,
        -8.97865782e-01,  1.19142684e+00],
       [ 1.15951308e+00,  1.30644169e+00, -9.95956516e-01,
        -3.07658213e-01,  8.41382601e-01],
       [-3.88202705e-01,  1.71012787e+00,  1.00405990e+00,
         2.82549357e-01,  8.41382601e-01]])

# model building

# linear regression

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
model=LinearRegression()

In [30]:
model.fit(xtrain_scaled,ytrain)

LinearRegression()

In [31]:
model.coef_

array([ 7.38840172, 17.65849082,  0.28817966,  0.81669598,  0.55174005])

In [32]:
model.intercept_

np.float64(55.12889339073183)

# prediction

In [33]:
xtest_scaled=scaler.transform(xtest)

In [34]:
xtest_scaled

array([[-3.88202705e-01, -1.28868376e+00,  1.00405990e+00,
         2.82549357e-01, -1.60892705e+00],
       [ 1.54644202e+00,  1.71012787e+00, -9.95956516e-01,
        -8.97865782e-01,  4.91338364e-01],
       [-1.16206060e+00, -1.11567539e+00,  1.00405990e+00,
         8.72756927e-01, -9.08838580e-01],
       ...,
       [ 1.15951308e+00, -4.81311398e-01, -9.95956516e-01,
        -8.97865782e-01,  8.41382601e-01],
       [-3.88202705e-01,  1.13343332e+00, -9.95956516e-01,
        -3.07658213e-01, -5.58794344e-01],
       [-1.27375951e-03, -5.38980852e-01, -9.95956516e-01,
         1.46296450e+00, -1.60892705e+00]])

In [35]:
ypred=model.predict(xtest_scaled)
ypred

array([29.13688262, 96.00369877, 27.34266324, ..., 54.6405356 ,
       71.42883093, 45.62196723])

In [36]:
ytest

6918    28.0
3140    97.0
7667    28.0
921     28.0
966     33.0
        ... 
4533    49.0
9647    56.0
7220    54.0
3773    71.0
6581    45.0
Name: Performance Index, Length: 1975, dtype: float64

# Evaluation

In [37]:
from sklearn.metrics import mean_squared_error

In [38]:
mean_squared_error(ytest,ypred)

4.20441253732261

In [39]:
y.min()

10.0

In [40]:
y.max()

100.0

# saving the model

In [41]:
import joblib
joblib.dump(model,"model.pk1")
joblib.dump(encoder,"encoder.pk1")
joblib.dump(scaler,"scaler.pk1")

['scaler.pk1']