In [92]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [93]:
df=pd.read_csv("C:\\Users\\RIYANA\\OneDrive\\New folder\\laptop_price.csv",encoding="latin1")
df

laptop_ID Company                              Product  \
0             1   Apple                          MacBook Pro   
1             2   Apple                          Macbook Air   
2             3      HP                               250 G6   
3             4   Apple                          MacBook Pro   
4             5   Apple                          MacBook Pro   
...         ...     ...                                  ...   
1298       1316  Lenovo                       Yoga 500-14ISK   
1299       1317  Lenovo                       Yoga 900-13ISK   
1300       1318  Lenovo                   IdeaPad 100S-14IBR   
1301       1319      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon   
1302       1320    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)   

                TypeName  Inches                            ScreenResolution  \
0              Ultrabook    13.3          IPS Panel Retina Display 2560x1600   
1              Ultrabook    13.3                                    1440x900   
2               Notebook    15.6                           Full HD 1920x1080   
3              Ultrabook    15.4          IPS Panel Retina Display 2880x1800   
4              Ultrabook    13.3          IPS Panel Retina Display 2560x1600   
...                  ...     ...                                         ...   
1298  2 in 1 Convertible    14.0   IPS Panel Full HD / Touchscreen 1920x1080   
1299  2 in 1 Convertible    13.3  IPS Panel Quad HD+ / Touchscreen 3200x1800   
1300            Notebook    14.0                                    1366x768   
1301            Notebook    15.6                                    1366x768   
1302            Notebook    15.6                                    1366x768   

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD   
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage   
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD   
3                     Intel Core i7 2.7GHz  16GB            512GB SSD   
4                     Intel Core i5 3.1GHz   8GB            256GB SSD   
...                                    ...   ...                  ...   
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD   
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD   
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage   
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD   
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD   

                               Gpu       OpSys  Weight  Price_euros  
0     Intel Iris Plus Graphics 640       macOS  1.37kg      1339.69  
1           Intel HD Graphics 6000       macOS  1.34kg       898.94  
2            Intel HD Graphics 620       No OS  1.86kg       575.00  
3               AMD Radeon Pro 455       macOS  1.83kg      2537.45  
4     Intel Iris Plus Graphics 650       macOS  1.37kg      1803.60  
...                            ...         ...     ...          ...  
1298         Intel HD Graphics 520  Windows 10   1.8kg       638.00  
1299         Intel HD Graphics 520  Windows 10   1.3kg      1499.00  
1300             Intel HD Graphics  Windows 10   1.5kg       229.00  
1301            AMD Radeon R5 M330  Windows 10  2.19kg       764.00  
1302             Intel HD Graphics  Windows 10   2.2kg       369.00  

[1303 rows x 13 columns]

In [94]:
df.head()

laptop_ID Company      Product   TypeName  Inches  \
0          1   Apple  MacBook Pro  Ultrabook    13.3   
1          2   Apple  Macbook Air  Ultrabook    13.3   
2          3      HP       250 G6   Notebook    15.6   
3          4   Apple  MacBook Pro  Ultrabook    15.4   
4          5   Apple  MacBook Pro  Ultrabook    13.3   

                     ScreenResolution                         Cpu   Ram  \
0  IPS Panel Retina Display 2560x1600        Intel Core i5 2.3GHz   8GB   
1                            1440x900        Intel Core i5 1.8GHz   8GB   
2                   Full HD 1920x1080  Intel Core i5 7200U 2.5GHz   8GB   
3  IPS Panel Retina Display 2880x1800        Intel Core i7 2.7GHz  16GB   
4  IPS Panel Retina Display 2560x1600        Intel Core i5 3.1GHz   8GB   

                Memory                           Gpu  OpSys  Weight  \
0            128GB SSD  Intel Iris Plus Graphics 640  macOS  1.37kg   
1  128GB Flash Storage        Intel HD Graphics 6000  macOS  1.34kg   
2            256GB SSD         Intel HD Graphics 620  No OS  1.86kg   
3            512GB SSD            AMD Radeon Pro 455  macOS  1.83kg   
4            256GB SSD  Intel Iris Plus Graphics 650  macOS  1.37kg   

   Price_euros  
0      1339.69  
1       898.94  
2       575.00  
3      2537.45  
4      1803.60

In [95]:
df.isnull()

laptop_ID  Company  Product  TypeName  Inches  ScreenResolution    Cpu  \
0         False    False    False     False   False             False  False   
1         False    False    False     False   False             False  False   
2         False    False    False     False   False             False  False   
3         False    False    False     False   False             False  False   
4         False    False    False     False   False             False  False   
...         ...      ...      ...       ...     ...               ...    ...   
1298      False    False    False     False   False             False  False   
1299      False    False    False     False   False             False  False   
1300      False    False    False     False   False             False  False   
1301      False    False    False     False   False             False  False   
1302      False    False    False     False   False             False  False   

        Ram  Memory    Gpu  OpSys  Weight  Price_euros  
0     False   False  False  False   False        False  
1     False   False  False  False   False        False  
2     False   False  False  False   False        False  
3     False   False  False  False   False        False  
4     False   False  False  False   False        False  
...     ...     ...    ...    ...     ...          ...  
1298  False   False  False  False   False        False  
1299  False   False  False  False   False        False  
1300  False   False  False  False   False        False  
1301  False   False  False  False   False        False  
1302  False   False  False  False   False        False  

[1303 rows x 13 columns]

In [96]:
df.isnull().sum()

laptop_ID           0
Company             0
Product             0
TypeName            0
Inches              0
ScreenResolution    0
Cpu                 0
Ram                 0
Memory              0
Gpu                 0
OpSys               0
Weight              0
Price_euros         0
dtype: int64

In [97]:
df.duplicated().sum()

np.int64(0)

In [98]:
df.drop("Product", axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   laptop_ID         1303 non-null   int64  
 1   Company           1303 non-null   object 
 2   TypeName          1303 non-null   object 
 3   Inches            1303 non-null   float64
 4   ScreenResolution  1303 non-null   object 
 5   Cpu               1303 non-null   object 
 6   Ram               1303 non-null   object 
 7   Memory            1303 non-null   object 
 8   Gpu               1303 non-null   object 
 9   OpSys             1303 non-null   object 
 10  Weight            1303 non-null   object 
 11  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 122.3+ KB


In [100]:
from sklearn.preprocessing import LabelEncoder

In [102]:
df["Company"]=encoder.fit_transform(df["Company"])
df["TypeName"]=encoder.fit_transform(df["TypeName"])
df["ScreenResolution"]=encoder.fit_transform(df["ScreenResolution"])
df["Cpu"]=encoder.fit_transform(df["Cpu"])
df["Ram"]=encoder.fit_transform(df["Ram"])
df["Memory"]=encoder.fit_transform(df["Memory"])
df["Gpu"]=encoder.fit_transform(df["Gpu"])
df["OpSys"]=encoder.fit_transform(df["OpSys"])
df["Weight"]=encoder.fit_transform(df["Weight"])
df

laptop_ID  Company  TypeName  Inches  ScreenResolution  Cpu  Ram  \
0             1        1         4    13.3                23   65    8   
1             2        1         4    13.3                 1   63    8   
2             3        7         3    15.6                 8   74    8   
3             4        1         4    15.4                25   85    1   
4             5        1         4    13.3                23   67    8   
...         ...      ...       ...     ...               ...  ...  ...   
1298       1316       10         0    14.0                13   89    5   
1299       1317       10         0    13.3                19   89    1   
1300       1318       10         3    14.0                 0   34    3   
1301       1319        7         3    15.6                 0   89    7   
1302       1320        2         3    15.6                 0   34    5   

      Memory  Gpu  OpSys  Weight  Price_euros  
0          4   58      8      38      1339.69  
1          2   51      8      35       898.94  
2         16   53      4      74       575.00  
3         29    9      8      71      2537.45  
4         16   59      8      38      1803.60  
...      ...  ...    ...     ...          ...  
1298       4   47      5      78       638.00  
1299      29   47      5      41      1499.00  
1300      35   40      5      56       229.00  
1301      10   21      5     104       764.00  
1302      26   40      5     113       369.00  

[1303 rows x 12 columns]

In [103]:
x=df.drop("Price_euros",axis=1)
y=df["Price_euros"]

In [104]:
from sklearn.model_selection import train_test_split

In [105]:
x.shape

(1303, 11)

In [106]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=33)

In [107]:
xtrain.shape

(1042, 11)

In [108]:
xtest.shape

(261, 11)

In [109]:
ytrain.shape

(1042,)

In [110]:
ytest.shape

(261,)

In [111]:
from sklearn.preprocessing import StandardScaler

In [112]:
scaler=StandardScaler()

In [113]:
xtrain_scaled=scaler.fit_transform(xtrain)

In [114]:
xtrain.head()

laptop_ID  Company  TypeName  Inches  ScreenResolution  Cpu  Ram  Memory  \
822        831       10         4    14.0                15   97    8      29   
639        647        4         3    15.6                 5  102    1      12   
892        903       15         4    15.0                 8   97    8      16   
26          27        1         4    13.3                 1   62    8       2   
925        939        4         3    15.6                 0   68    5      26   

     Gpu  OpSys  Weight  
822   53      5      14  
639   75      5      92  
892   53      5      18  
26    51      3      36  
925   47      5      83

In [115]:
xtrain_scaled

array([[ 0.44578201,  0.88072317,  1.13487447, ..., -0.07515807,
         0.1824399 , -1.78048221],
       [-0.03869158, -0.60065463,  0.33151904, ...,  0.97604609,
         0.1824399 ,  0.03063995],
       [ 0.63535863,  2.11520468,  1.13487447, ..., -0.07515807,
         0.1824399 , -1.68760415],
       ...,
       [-0.20193812,  1.12761947, -1.27519183, ...,  1.21495613,
         0.1824399 ,  1.79532309],
       [-0.69694374, -1.09444723, -1.27519183, ...,  1.0238281 ,
         0.1824399 ,  1.74888406],
       [ 1.04347496,  0.14003427,  0.33151904, ..., -0.36185012,
         0.1824399 , -0.92136016]])

In [116]:
from sklearn.linear_model import LinearRegression

In [117]:
model=LinearRegression()

In [118]:
model.fit(xtrain_scaled,ytrain)

LinearRegression()

In [119]:
model.coef_

array([  63.64335517,   27.75740666,    2.74665422,  116.43642986,
        143.43984968,  226.81215772, -121.91954052,   81.123535  ,
        150.0346028 ,  135.97784207, -130.43804165])

In [120]:
model.intercept_

np.float64(1116.23613243762)

In [121]:
xtest_scaled=scaler.transform(xtest)

In [122]:
xtest_scaled

array([[ 1.59114076,  0.88072317,  0.33151904, ..., -0.07515807,
        -0.77767311,  0.70400589],
       [-1.50264438, -0.60065463,  1.13487447, ...,  0.30709799,
         0.1824399 , -1.59472609],
       [-1.25250856,  0.88072317, -2.07854727, ...,  0.30709799,
         0.1824399 , -0.94457967],
       ...,
       [-0.99447371,  0.88072317,  0.33151904, ...,  2.07503227,
        -0.77767311,  1.23805473],
       [ 0.27726945, -0.60065463, -1.27519183, ...,  1.21495613,
         0.1824399 ,  1.91142067],
       [-0.12821387,  2.36210098,  0.33151904, ..., -0.36185012,
         0.1824399 ,  0.51824977]])

In [123]:
ypred=model.predict(xtest_scaled)
ypred

array([1053.42668776, 1409.31981899, 1810.50082817,  451.16039632,
       1126.66753912, 1558.36406335, 1240.26206938, 1266.84896137,
       1429.98553748, 1624.50174442, 1392.94143156, 1280.9206035 ,
       1068.12416208, 1703.7772323 , 1480.62309287,  840.19398074,
        811.90888838, 1305.17915068, 1380.58580753,  932.61364839,
        846.87330833, 1272.58945066, 1411.43547607, 1661.59776661,
       1869.49303547,  232.95648854, -116.33017563, 1716.6618458 ,
        703.03445058, 1335.34716251, 1721.0470945 , 1477.98894754,
        728.59479036,  581.58590242,  977.91343425, 1161.28511863,
        -52.16004453, 1635.98333495, 1150.62854465, 1444.66501398,
        414.5426303 , 1001.16357784, 1529.7766609 , 1748.19485914,
        669.06525738, 1260.93428474, 1023.42054136,  721.39050832,
       1056.62492145, 1226.08072692,  -58.63969564,  902.69886971,
         54.46561815, 1130.3296024 ,  118.92574653, 1294.89887394,
        723.67743814,  904.61455063,  335.32732319, 1040.28142

In [124]:
ytest

1248     573.00
89      1649.00
182     1849.00
475      740.00
1201     629.00
         ...   
642     2450.00
302      649.00
279      849.00
758     2868.99
606     1399.00
Name: Price_euros, Length: 261, dtype: float64

In [125]:
from sklearn.metrics import mean_squared_error

In [126]:
mean_squared_error(ytest,ypred)

347475.8652241133

In [127]:
y.min()

174.0

In [128]:
y.max()

6099.0

In [129]:
import joblib
joblib.dump(model,"model.pk1")
joblib.dump(encoder,"encoder.pk1")
joblib.dump(scaler,"scaler.pk1")

['scaler.pk1']